continuation_prompt = '[❯] (fg:#a675d8)'
add_newline = true
right_format = """$time$username"""

[character]
success_symbol = '[❯](fg:cyan)'
error_symbol = '[❯](fg:magenta)'

[time]
disabled = false
format = '[$time]($style) '
style = "fg:#888888"

[cmd_duration]
show_milliseconds = false
style = "fg:#aaaaaa"
format = ' [󱫌 $duration]($style)'

[directory]
style = "fg:blue"
format = "[$path ]($style)"
truncation_length = 4
truncation_symbol = "..."
truncate_to_repo = false
read_only = " 󰌾"

[username]
style_root = "bold fg:grey"
style_user = "fg:grey"
format = "[$user ]($style)"

[git_status]
style = "fg:blue"
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_branch]
format = " [$symbol $branch ]($style)"
style = "fg:#888888"
symbol = ""

[git_metrics]
disabled = true
added_style = 'bold blue'
format = '\([+$added]($added_style)\[-$deleted\]($deleted_style)\) '

[package]
symbol = "󰏗 "

[nodejs]
style = "#ffc0cb"
format = "[$symbol$version ]($style)"
symbol = " "

[python]
detect_extensions = ['py', 'ipynb']
pyenv_version_name = true
style = "yellow"
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[java]
format = ' [${symbol}(${version} )]($style)'
symbol = " "

[aws]
format = '[$symbol$profile]($style) '
style = 'yellow'
symbol = " "
[aws.region_aliases]
ap-northeast-1 = 'apn1'

[gcloud]
disabled = true
format = '[$symbol$project]($style)'
symbol = " "
[gcloud.region_aliases]
asia-northeast1 = 'asn1'

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
