# bind-key x kill-pane # Not require comfirmation

setw -g mode-keys vi

set -g default-terminal "xterm-256color"
set -g escape-time 0

set -g mouse on
set -g focus-events on

set-option -g prefix C-b
set-option -g repeat-time 500
set-option -g focus-events on

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

set -g window-status-current-format "#I:#W#F"
set -g window-status-current-style "bg=color025,fg=color015"

bind-key r set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

bind-key 'C-h' select-pane -L
bind-key 'C-j' select-pane -D
bind-key 'C-k' select-pane -U
bind-key 'C-l' select-pane -R

bind-key -r C-n next-window
bind-key -r C-p previous-window
